# Generated by Django 4.0 on 2022-01-31 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Customer_Name', models.CharField(max_length=25)),
                ('Vehicle_Number', models.CharField(blank=True, max_length=15, null=True)),
                ('Email', models.EmailField(default=None, max_length=254)),
                ('Phone_No', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('Manager_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Manager_Name', models.CharField(max_length=50)),
                ('No_Of_Waiters', models.IntegerField()),
            ],
            options={
                'db_table': 'Manager',
            },
        ),
        migrations.CreateModel(
            name='Menu_NonVeg',
            fields=[
                ('Item_ID_NonVeg', models.AutoField(primary_key=True, serialize=False)),
                ('Item_Name', models.CharField(max_length=50)),
                ('Item_Price', models.IntegerField()),
                ('Cuisine_Type', models.CharField(max_length=50)),
                ('Image', models.ImageField(default=None, upload_to='')),
            ],
            options={
                'db_table': 'Menu_NonVeg',
            },
        ),
        migrations.CreateModel(
            name='Menu_Veg',
            fields=[
                ('Item_ID_Veg', models.AutoField(primary_key=True, serialize=False)),
                ('Item_Name', models.CharField(max_length=50)),
                ('Item_Price', models.IntegerField()),
                ('Cuisine_Type', models.CharField(max_length=50)),
                ('Image', models.ImageField(default=None, upload_to='')),
            ],
            options={
                'db_table': 'Menu_Veg',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=50)),
                ('password2', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Register',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('Restaurant_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Phone_No', models.CharField(max_length=12)),
                ('Table_Price', models.IntegerField()),
                ('Type', models.CharField(max_length=25)),
                ('Image', models.ImageField(default=None, upload_to='')),
            ],
            options={
                'db_table': 'Restaurant',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('Table_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Table_Type', models.CharField(max_length=20)),
                ('No_Of_Seats', models.IntegerField()),
            ],
            options={
                'db_table': 'Table',
            },
        ),
        migrations.CreateModel(
            name='Valet',
            fields=[
                ('Valet_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Valet_Name', models.CharField(max_length=25)),
                ('No_Of_Vehicles', models.IntegerField(default=0)),
                ('Manager_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrsapp.manager')),
            ],
            options={
                'db_table': 'Valet',
            },
        ),
        migrations.CreateModel(
            name='Meals_Order',
            fields=[
                ('Meal_No', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(default=1)),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrsapp.customer')),
                ('Item_NonVeg', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rrsapp.menu_nonveg')),
                ('Item_Veg', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rrsapp.menu_veg')),
                ('Manager_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrsapp.manager')),
            ],
            options={
                'db_table': 'Meals_Order',
            },
        ),
        migrations.AddField(
            model_name='manager',
            name='Restaurant_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrsapp.restaurant'),
        ),
        migrations.AddField(
            model_name='customer',
            name='Valet_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrsapp.valet'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Booking_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrsapp.customer')),
                ('Manager_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrsapp.manager')),
                ('Restaurant_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrsapp.restaurant')),
                ('Table_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrsapp.table')),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
    ]
