# Generated by Django 4.0 on 2022-01-31 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals_order',
            name='Booking_ID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rrsapp.booking'),
        ),
    ]
