# Generated by Django 4.0 on 2022-01-31 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrsapp', '0002_meals_order_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals_order',
            name='Customer_ID',
        ),
        migrations.RemoveField(
            model_name='meals_order',
            name='Manager_ID',
        ),
    ]
