# Generated by Django 4.0 on 2022-02-02 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrsapp', '0003_remove_meals_order_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals_order',
            name='Item_NonVeg',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrsapp.menu_nonveg'),
        ),
    ]
