# Generated by Django 4.0 on 2022-02-02 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rrsapp', '0004_alter_meals_order_item_nonveg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals_order',
            name='Item_NonVeg',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrsapp.menu_nonveg'),
        ),
        migrations.AlterField(
            model_name='meals_order',
            name='Item_Veg',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rrsapp.menu_veg'),
        ),
    ]
