# Generated by Django 4.0 on 2022-01-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('Restaurant_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Phone_No', models.CharField(max_length=12)),
                ('Table_Price', models.IntegerField()),
                ('Type', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Restaurant',
            },
        ),
    ]
