# Generated by Django 4.0 on 2022-01-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0002_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('Table_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Table_Type', models.CharField(max_length=20)),
                ('No_Of_Seats', models.IntegerField()),
            ],
            options={
                'db_table': 'Table',
            },
        ),
    ]
