# Generated by Django 4.0 on 2022-01-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0003_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_NonVeg',
            fields=[
                ('Item_ID_NonVeg', models.AutoField(primary_key=True, serialize=False)),
                ('Item_Name', models.CharField(max_length=50)),
                ('Item_Price', models.IntegerField()),
                ('Cuisine_Type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Menu_NonVeg',
            },
        ),
        migrations.CreateModel(
            name='Menu_Veg',
            fields=[
                ('Item_ID_Veg', models.AutoField(primary_key=True, serialize=False)),
                ('Item_Name', models.CharField(max_length=50)),
                ('Item_Price', models.IntegerField()),
                ('Cuisine_Type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Menu_Veg',
            },
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('Manager_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Manager_Name', models.CharField(max_length=50)),
                ('No_Of_Waiters', models.IntegerField()),
                ('Restaurant_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dbmsapp.restaurant')),
            ],
            options={
                'db_table': 'Manager',
            },
        ),
    ]
