# Generated by Django 4.0 on 2022-01-15 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0004_menu_nonveg_menu_veg_alter_register_email_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Customer_Name', models.CharField(max_length=25)),
                ('Vehicle_Number', models.CharField(max_length=15)),
                ('Phone_No', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.AlterField(
            model_name='manager',
            name='Restaurant_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsapp.restaurant'),
        ),
        migrations.CreateModel(
            name='Valet',
            fields=[
                ('Valet_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Valet_Name', models.CharField(max_length=25)),
                ('No_Of_Vehicles', models.IntegerField(default=0)),
                ('Manager_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsapp.manager')),
            ],
            options={
                'db_table': 'Valet',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('Meal_No', models.AutoField(primary_key=True, serialize=False)),
                ('Total_Price', models.IntegerField()),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsapp.customer')),
                ('Manager_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsapp.manager')),
            ],
            options={
                'db_table': 'Meal',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='Valet_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsapp.valet'),
        ),
    ]
