# Generated by Django 4.0 on 2022-01-15 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0005_customer_alter_manager_restaurant_id_valet_meal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Booking_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsapp.customer')),
                ('Manager_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsapp.manager')),
                ('Restaurant_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsapp.restaurant')),
                ('Table_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsapp.table')),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
    ]
