# Generated by Django 4.0 on 2022-01-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0007_alter_register_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='Image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
