# Generated by Django 4.0 on 2022-01-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0008_restaurant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='Total_Price',
        ),
        migrations.AddField(
            model_name='meal',
            name='Item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dbmsapp.menu_nonveg'),
        ),
        migrations.AddField(
            model_name='meal',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
    ]
