# Generated by Django 4.0 on 2022-01-20 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0009_remove_meal_total_price_meal_item_meal_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('Meal_No', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(default=1)),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsapp.customer')),
                ('Item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dbmsapp.menu_nonveg')),
                ('Manager_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsapp.manager')),
            ],
            options={
                'db_table': 'Meals',
            },
        ),
    ]
