# Generated by Django 4.0 on 2022-01-20 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0010_meals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal_Order',
            fields=[
                ('Meal_No', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(default=1)),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsapp.customer')),
                ('Item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dbmsapp.menu_nonveg')),
                ('Manager_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmsapp.manager')),
            ],
            options={
                'db_table': 'Meal_Order',
            },
        ),
    ]
