# Generated by Django 4.0 on 2022-01-20 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0011_meal_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal_order',
            old_name='Item',
            new_name='Item_NonVeg',
        ),
        migrations.AddField(
            model_name='meal_order',
            name='Item_Veg',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dbmsapp.menu_veg'),
        ),
    ]
