# Generated by Django 4.0 on 2022-01-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0013_meals_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_nonveg',
            name='Image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='menu_veg',
            name='Image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
