# Generated by Django 4.0 on 2022-01-22 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0014_menu_nonveg_image_menu_veg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Email',
            field=models.EmailField(default='XXXX@YYY.ZZZ', max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Valet_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dbmsapp.valet'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Vehicle_Number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
