# Generated by Django 4.0 on 2022-01-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsapp', '0015_customer_email_alter_customer_valet_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
